### PR TITLE
add prow file

### PR DESCRIPTION
**Pull request by songleo**
https://github.com/open-cluster-management/backlog/issues/10603

### CODE REVIEW

**Comment by clyang82** [comment]
`We left an override in osci/publish for repos that need to publish more than one image.  The var names are  OSCI_COMPONENT_NAME and OSCI_COMPONENT_VERSION.` I would propose to use environment vars instead of put these files here.

**Comment by songleo** [comment]
@clyang82 I have removed `COMPONENT_NAME` and `COMPONENT_VERSION` files. pls help review it. thanks

**Pull request merged**
