### PR TITLE
Update Prometheus Alertmanager to v0.25.0

### PR DESCRIPTION
**Pull request by dislbenn**
Update the Prometheus Alert-manager to v0.25.0.

### CODE REVIEW

**Comment by dislbenn** [comment]
/override ci/prow/sonar-pre-submit

Overriding the sonar job for further debugging. The tests in the sonar job are passing; however, the job is failing. I will open up an issue to continue further investigation.

**Review by subbarao-meduri — APPROVED** [review]
/lgtm

**Pull request merged**
